name: Test with Sonar 
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

          
      - name: Install dependencies for cancel_sales
        run: |
          cd cancel_sales/
          pip install -r requirements.txt

      - name: Install dependencies for change_status_category_or_product/
        run: |
          cd change_status_category_or_product/
          pip install -r requirements.txt

      - name: Install dependencies for get_category
        run: |
          cd get_category/
          pip install -r requirements.txt

      - name: Install dependencies for get one product
        run: |
          cd get_one_product/
          pip install -r requirements.txt
          
      - name: Install dependencies for get products
        run: |
          cd get_products/
          pip install -r requirements.txt

      - name: Install dependencies for save category
        run: |
          cd save_category/
          pip install -r requirements.txt

      - name: Install dependencies for save sale
        run: |
          cd save_sale/
          pip install -r requirements.txt

      - name: Install dependencies for update product
        run: |
          cd update_product/
          pip install -r requirements.txt

      - name: Install dependencies for history of sales
        run: |
          cd view_sales_history_per_day/
          pip install -r requirements.txt
  
      - name: Install dependencies 
        run: |
          cd test/
          pip install -r requirements.txt

      - name: Run unit tests and generate coverage report
        run: |
          pytest --cov=SRC --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
