name: Test with Sonar 
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r cancel_sales/requirements.txt
          pip install -r change_status_category_or_product/requirements.txt
          pip install -r get_category/requirements.txt
          pip install -r get_one_product/requirements.txt
          pip install -r get_products/requirements.txt
          pip install -r save_category/requirements.txt
          pip install -r save_sale/requirements.txt
          pip install -r update_product/requirements.txt
          pip install -r view_sales_history_per_day/requirements.txt
          pip install -r test/requirements.txt

      - name: Set PYTHONPATH
        run: |
          PYTHONPATH=$(pwd)/cancel_sales:$(pwd)/change_status_category_or_product:$(pwd)/get_category:$(pwd)/get_one_product:$(pwd)/get_products:$(pwd)/login:$(pwd)/newPassword:$(pwd)/save_category:$(pwd)/save_sale:$(pwd)/update_product:$(pwd)/view_sales_history_per_day
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV


      - name: Run unit tests and generate coverage report
        run: |
          pytest --cov=. --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

