name: Test with Sonar

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          # Instalar dependencias desde los requirements.txt de todas las carpetas relevantes
          pip install -r cancel_sales/requirements.txt
          pip install -r change_status_category_or_product/requirements.txt
          pip install -r get_category/requirements.txt
          pip install -r get_one_product/requirements.txt
          pip install -r get_products/requirements.txt
          pip install -r login/requirements.txt
          pip install -r newPassword/requirements.txt
          pip install -r save_category/requirements.txt
          pip install -r save_sale/requirements.txt
          pip install -r update_product/requirements.txt
          pip install -r view_sales_history_per_day/requirements.txt
          pip install -r test/requirements.txt

      - name: List directory contents
        run: |
          ls -R /home/runner/work/Servicios_Cafe_Balu

      - name: Run tests and generate coverage
        working-directory: /home/runner/work/Servicios_Cafe_Balu/Servicios_Cafe_Balu
        run: |
          pytest --cov=cancel_sales --cov=change_status_category_or_product --cov=get_category --cov=get_one_product --cov=get_products --cov=login --cov=newPassword --cov=save_category --cov=save_sale --cov=update_product --cov=view_sales_history_per_day --cov-report=xml --cov-report=term

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
